version: '3'
services:
  worker:
    image: bmarmet/worker
    depends_on:
      - redis
  redis:
    image: redis:3.2-alpine
  monitor:
    image: bmarmet/monitor
    ports:
      - 4000:3000
  dispatcher:
    image: bmarmet/dispatcher
    ports:
      - 3000:3000